version: '3.4'

services:
  server:
    image: server
    build:
      context: .
    
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001  
    depends_on: 
     - "mongodb"  

  mongodb:
   image: mongo
   ports:
    - 27017:27017

           
